[package]
name = "dotclock"
version = "0.1.0"
edition = "2024"

[dependencies]
time = {version = "0.3.41", features = ["std", "parsing", "macros"]}
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
crossterm = "0.28"
ratatui = "0.29"
